---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: '.chef-zero/environments'
  data_bags_path: '.chef-zero/data_bags'
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: stage

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[et_upload::default]
    attributes:
