---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: test/integration/default/encrypted_data_bag_secret
  client_rb:
    environment: test

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[et_upload::default]
    attributes:
