---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: test

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[et_upload::default]
    attributes:
