#!/usr/bin/env ruby

require 'yaml'

conf = YAML.load_file('/etc/evertrue/config.yml')

files = conf['unames'].map { |uname| Dir.glob("/home/#{uname}/uploads/*.{csv,gz,zip}") }.flatten

puts files.join("\n")
